### ISSUE TITLE
Error: Cannot find module 'shelljs' on Windows 8.1

### ISSUE THREAD

**Issue by jmartsch** [fixate/pw-mvc-boilerplate#28]
Hi. I cloned the git repo and changed into the directory and linked as described.
After that I created a new folder and ran ```yo fixate-pw``` and I get an error "Error: Cannot find module 'shelljs'". So I ran  ```npm install -g shelljs```  but after running ```yo fixate-pw``` again I still get the same error message. Any ideas how to solve this?

```javascript
Error: Cannot find module 'shelljs'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\lib\git-utils.coffee:3:9)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\lib\git-utils.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\generator.coffee:1:12)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\generator.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:16:19)
  at Module.load (W:\wamp\www\generator-fixate-pw\node_modules\coffee-script\lib\coffee-script\register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (W:\wamp\www\generator-fixate-pw\app\index.js:3:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object._storeAsPath.Object.defineProperty.get [as fixate-pw:app] (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:40:23)
  at Store.get (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\store.js:64:35)
  at Environment.get (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:228:16)
  at Environment.create (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:246:24)
  at Environment.run (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\environment.js:318:24)
  at C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:86:9
  at Environment.resolver.lookup (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-environment\lib\resolver.js:50:12)
  at init (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:61:7)
  at pre (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:48:3)
  at Object.<anonymous> (C:\Users\Aceman\AppData\Roaming\npm\node_modules\yo\lib\cli.js:150:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:901:3
```

**Comment by larrybotha** [comment]
if you're running the generator you won't need to clone this repo - the generator will do all the dirty work for you, all in one place :)

All you'll need to do is create a directory, cd into it, and run the generator.

I'm guessing you've already cloned and linked the fixate-pw generator - cd into the generator's directory and install shelljs directly from there:

```shell
$ npm install shelljs
```

After doing this, does the generator run? If so, there may be a problem with where npm is installing global modules, and where Windows is looking for those modules.

This generator is developed on Unix machines, so I'm not sure if there's some environment specific issue. Perhaps the generator needs shelljs as a dependency.

Nonetheless - I would attempt getting shelljs running somewhere, perhaps a small node app which simply logs console output when it runs.

**Comment by larrybotha** [comment]
@jmartsch Can you open this on the generator's repo, rather?

**Comment by jmartsch** [comment]
Thanks for the quick answer. I opened this on the generator´s repo.
